### PR TITLE
take into account luadev config

### PR DESCRIPTION
**Pull request by sp4ke**
Hi, sorry my last fix was still not working I had to dig deeper and found that the luadev generated config was never included/merged.

### CODE REVIEW

**Comment by ray-x** [comment]
Did you push your changes?

**Comment by sp4ke** [comment]
yes in this PR sho

**Comment by sp4ke** [comment]
Yes this PR should be good

**Comment by ray-x** [comment]
Strange, as it shows there are no files changed for the PR.

**Comment by sp4ke** [comment]
Yes strange, the change was here 
https://github.com/ray-x/navigator.lua/pull/230/commits/c84b2964f9646b9c935af01ba1f02f1c30b7d457

Side note, this has enabled navigator to setup luadev and take into account the extra workspaces I define but I still cannot get the help signature for vim internal apis to work. I don't know if I am missing something or just a problem from luadev with nightly neovim.

**Comment by ray-x** [comment]
Is it because that commit was already merged?

**Comment by sp4ke** [comment]
I just pushed an extra commit on my github branch and then used the GH button to pull the changes and make a PR, I didn't do any manual merge locally

**Comment by ray-x** [comment]
I think it is duplicated as this PR:
https://github.com/ray-x/navigator.lua/pull/229/files
So GitHub shows there were no changes

**Comment by sp4ke** [comment]
Yes it is I will close this one then.

**Pull request closed without merging**
